//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by André Sanches Bocato on 18/02/19.
//  Copyright © 2019 André Sanches Bocato. All rights reserved.
//

import Foundation

struct Student: Codable {
    
    let objectId: String    // generated by Parse, identifies location
    let uniqueKey: String?  // populate with Udacity account id
    let firstName: String
    let lastName: String
    let mapString: String
    let mediaURL: String
    let latitude: Double
    let longitude: Double
    
//    enum CodingKeys: String, CodingKey {
//        case objectID = "objectId"
//        case email, key
//    }
    
}
